spring:
  application:
    name: currency-converter-service
  datasource:
    url: jdbc:postgresql://localhost:5432/currency_transfer
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: 8083

exchange:
  rate:
    service:
      url: https://www.cbr-xml-daily.ru

currencies:
  codes:
    AED: "Дирхам ОАЭ"
    AMD: "Армянский драм"
    AUD: "Австралийский доллар"
    AZN: "Азербайджанский манат"
    BGN: "Болгарский лев"
    BRL: "Бразильский реал"
    BYN: "Белорусский рубль"
    CAD: "Канадский доллар"
    CHF: "Швейцарский франк"
    CNY: "Китайский юань"
    CZK: "Чешская крона"
    DKK: "Датская крона"
    EGP: "Египетский фунт"
    EUR: "Евро"
    GBP: "Фунт стерлингов Соединенного королевства"
    GEL: "Грузинский лари"
    HKD: "Гонконгский доллар"
    HUF: "Венгерский форинт"
    IDR: "Индонезийская рупия"
    INR: "Индийская рупия"
    JPY: "Японская иена"
    KGS: "Киргизский сом"
    KRW: "Южнокорейская вона"
    KZT: "Казахстанский тенге"
    MDL: "Молдавский лей"
    NOK: "Норвежская крона"
    NZD: "Новозеландский доллар"
    PLN: "Польский злотый"
    QAR: "Катарский риал"
    RON: "Румынский лей"
    RSD: "Сербский динар"
    RUB: "Российский рубль"
    SEK: "Шведская крона"
    SGD: "Сингапурский доллар"
    THB: "Таиландский бат"
    TJS: "Таджикский сомони"
    TMT: "Новый туркменский манат"
    TRY: "Турецкая лира"
    UAH: "Украинская гривна"
    USD: "Доллар США"
    UZS: "Узбекский сум"
    VND: "Вьетнамский донг"
    XDR: "СДР (специальные права заимствования)"
    ZAR: "Южноафриканский рэнд"
